### ISSUE TITLE
Issue with placing and "destroying" water and lava

### ISSUE THREAD

**Issue by xDParis64** [JimiIT92/UniverseGuard2#169] opened 2021-03-18 21:11 UTC
In my server when a player tries to pick up water it doesn't let them and says they don't have permission and the water places back down however it also goes into the bucket and when the player than places down the water it places down but then says they do not have the permissions for that which then refills the bucket, this is a global flag issue as they can destroy blocks and place blocks in the same place 

Please Help :)

{
  "VERSION": 2.33,
  "ID": "37ee5b2e-1ae0-471a-93c2-1649d555006b",
  "TYPE": "GLOBAL",
  "NAME": "StoneBlock2",
  "GAMEMODE": "minecraft:not_set",
  "FLAGS": [
    {
      "name": "place",
      "value": true
    },
    {
      "name": "destroy",
      "value": true
    },
    {
      "name": "pvp",
      "value": true
    },
    {
      "name": "expdrop",
      "value": true
    },
    {
      "name": "itemdrop",
      "value": true
    },
    {
      "name": "itempickup",
      "value": true
    },
    {
      "name": "enderpearl",
      "value": true
    },
    {
      "name": "sleep",
      "value": true
    },
    {
      "name": "lighter",
      "value": true
    },
    {
      "name": "chests",
      "value": true
    },
    {
      "name": "trappedchests",
      "value": true
    },
    {
      "name": "waterflow",
      "value": true
    },
    {
      "name": "lavaflow",
      "value": true
    },
    {
      "name": "otherliquidsflow",
      "value": true
    },
    {
      "name": "leafdecay",
      "value": true
    },
    {
      "name": "firespread",
      "value": true
    },
    {
      "name": "potionsplash",
      "value": true
    },
    {
      "name": "falldamage",
      "value": true
    },
    {
      "name": "cantp",
      "value": true
    },
    {
      "name": "canspawn",
      "value": true
    },
    {
      "name": "hunger",
      "value": true
    },
    {
      "name": "enderchests",
      "value": true
    },
    {
      "name": "walldamage",
      "value": true
    },
    {
      "name": "drown",
      "value": true
    },
    {
      "name": "invincible",
      "value": false
    },
    {
      "name": "cactusdamage",
      "value": true
    },
    {
      "name": "firedamage",
      "value": true
    },
    {
      "name": "endermangrief",
      "value": true
    },
    {
      "name": "enderdragonblockdamage",
      "value": true
    },
    {
      "name": "hidelocation",
      "value": false
    },
    {
      "name": "hideflags",
      "value": false
    },
    {
      "name": "hidemembers",
      "value": false
    },
    {
      "name": "hideregion",
      "value": false
    },
    {
      "name": "icemelt",
      "value": true
    },
    {
      "name": "exit",
      "value": true
    },
    {
      "name": "enter",
      "value": true
    },
    {
      "name": "vinesgrowth",
      "value": true
    },
    {
      "name": "sendchat",
      "value": true
    },
    {
      "name": "trample",
      "value": true
    },
    {
      "name": "shulkerboxes",
      "value": true
    },
    {
      "name": "pistons",
      "value": true
    },
    {
      "name": "frostwalker",
      "value": true
    },
    {
      "name": "fishingpole",
      "value": true
    }
  ],
  "INTERACTS": [
    {
      "BLOCK": "craftingtable",
      "USE": true
    },
    {
      "BLOCK": "enchantingtable",
      "USE": true
    },
    {
      "BLOCK": "itemframe",
      "USE": true
    },
    {
      "BLOCK": "armorstand",
      "USE": true
    },
    {
      "BLOCK": "anvil",
      "USE": true
    },
    {
      "BLOCK": "hopper",
      "USE": true
    },
    {
      "BLOCK": "lever",
      "USE": true
    },
    {
      "BLOCK": "button",
      "USE": true
    },
    {
      "BLOCK": "furnace",
      "USE": true
    },
    {
      "BLOCK": "door",
      "USE": true
    },
    {
      "BLOCK": "fencegate",
      "USE": true
    },
    {
      "BLOCK": "trapdoor",
      "USE": true
    },
    {
      "BLOCK": "pressureplate",
      "USE": true
    },
    {
      "BLOCK": "sign",
      "USE": true
    }
  ],
  "VEHICLES": [
    {
      "VEHICLE": "minecart",
      "PLACE": true,
      "DESTROY": true
    },
    {
      "VEHICLE": "boat",
      "PLACE": true,
      "DESTROY": true
    }
  ],
  "EXPLOSIONS": [
    {
      "EXPLOSION": "tnt",
      "DAMAGE": true,
      "DESTROY": true
    },
    {
      "EXPLOSION": "creeper",
      "DAMAGE": true,
      "DESTROY": true
    },
    {
      "EXPLOSION": "endercrystal",
      "DAMAGE": true,
      "DESTROY": true
    },
    {
      "EXPLOSION": "fireball",
      "DAMAGE": true,
      "DESTROY": true
    },
    {
      "EXPLOSION": "enderdragon",
      "DAMAGE": true,
      "DESTROY": true
    },
    {
      "EXPLOSION": "otherexplosions",
      "DAMAGE": true,
      "DESTROY": true
    }
  ],
  "MOBS": [],
  "COMMANDS": [],
  "EXCLUDED_BLOCKS": {
    "PLACE": [water, lava],
    "DESTROY": [water, lava]
  },
  "DISALLOWED_ITEMS": [],
  "DISALLOWED_BLOCKS": [],
  "TEMPLATE": false

**Comment by SidewinderDX** [comment] 2021-03-19 13:46
Duplicate of #153 

Issue Is known and should be fixed in the next Update. 
JimiIT92 already described the reasons for it . :)

**Closed** 2021-03-20 18:14 UTC
Labels: Fixed - To Be Release in next version, duplicate

**Comment by JimiIT92** [comment] 2021-03-21 20:12
Version 2.34 has just been released, and it contains some changes to how picking/placing fluids works. Check it out here! ;)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.34
