### ISSUE TITLE
Bug with itemDrop flag

### ISSUE THREAD

**Issue by XuTTcTeP** [JimiIT92/UniverseGuard2#125] opened 2020-08-23 13:07 UTC
Hi!
When you deny itemDrop flag in region you can still drop items. All you need to do is open inventory, click on item and press escape button, so item will drop :) Please fix this.

**Comment by JimiIT92** [comment] 2020-09-04 10:47
Hi, I've tested this and what I got is that the item get destroyed, as by design. So if you can please share me the region file, as it could happen with a particular region configuration, that would be helpful

**Comment by XuTTcTeP** [comment] 2020-09-14 11:01
Sorry for being late. Try to represent it in survival mode. Here is rg file(cant attach it to github) : https://mega.nz/file/QVpljT4A#Q4dnG-7CFZbOwmWAevyAq4gKF7F5r_mc-C5NxfTqbsI

**Comment by XuTTcTeP** [comment] 2020-09-14 11:03
I've tested it in creative mode, and items have actually been destroyed. So, here is the problem, i suppose

**Comment by JimiIT92** [comment] 2020-09-14 12:28
Thank you for the Region file and the video (very helpful)! I will try as soon as I can to see if I can reproduce the issue and understand why it happens

**Comment by XuTTcTeP** [comment] 2020-09-14 13:41
Sorry for misunderstand. I'm attaching new region file: https://mega.nz/file/EYJGia4J#wZbMio4WLXn5KH-PCXotRLnK-S58fUJoZUCZxuS0iOg

**Comment by JimiIT92** [comment] 2020-09-15 10:31
Thank you for the file, it really helped to identify the issue that should now be resolved in version 2.27! 
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.27

**Closed by JimiIT92** 2020-09-15 10:31 UTC

**Comment by Vulant** [comment] 2021-01-12 01:32
I just want to say, thank you for the fix and thank you for reporting this issue. I just discovered this bug which would have completely broke a mechanic I'm working on, I'm so glad this was reported before me and fixed.

**Comment by Vulant** [comment] 2021-01-12 01:46
I also want to note, that if players spam-attempt trying to throw items out of their inventory using the method described above, that item can disappear / be deleted. If it reappears on your cursor or in your inventory, it could be a ghost-image. Clicking on the item again would make it disappear. Not an issue for me but may be an issue for others.
