### ISSUE TITLE
'Could not pass MoveEntityEvent' after world creation [1.12.2] [SF 2705-7.1.0-BETA-3206]

### ISSUE THREAD

**Issue by DiggyNevs** [JimiIT92/UniverseGuard2#51] opened 2018-08-11 07:54 UTC
After creation a new world with any world management plugin (Nucleus, Project Worlds) UniverseGuard doesn't add this to the config file until after a reboot of the server, and will output `Could not pass MoveEntityEvent` for every movement and interaction executed in said world. 
Especially when this world is directly needed this is not only causing spam in the console, but also causes TPS lag due to the amount of messages sent per tick (with the appropriate amount of players this goes up a lot). 
My scenario : members can create a private world and use it for their build creations, but when they do the console gets spammed and occasionally starts lagging.

Versions : 
UG2 : 2.14-1.12.2
SF : 2705-7.1.0-BETA-3206 (latest recommended)

I will of course be available for testing if you need me to.

**Comment by JimiIT92** [comment] 2018-09-30 16:56
Sorry for the really late answer, it's been a crazy period at my work 😅 I've looked into the issue and seems that adding more checks to the waterflow flag could possibly solve the problem. I walked into new worlds for an hour trying to get the spam, but no message were thrown in the console. I saw another report of this error where it was the stack trace in it, and i've the check to fix the error in that trace, so i believe that is the cause of the spam. Let me know if this bug will still occur in version 2.16 when it will be released later today ;)

**Closed by JimiIT92** 2018-09-30 16:56 UTC

**Comment by JimiIT92** [comment] 2018-09-30 19:38
Version 2.16 released! Check it here ;) [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/177](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/177)
