### ISSUE TITLE
"/rg flag mobspawn all false" Not Saving in Config & Mobs Still Spawn

### ISSUE THREAD

**Issue by spruill7716** [JimiIT92/UniverseGuard2#31] opened 2018-04-22 23:57 UTC
I'm trying to disable all mobs within a region using "/rg flag mobspawn all false" however UniverseGuard is not saving the edit and mobs are still spawning within the region. I included a number of screenshots showing the process I went through, as well as a screenshot of the config file of the local region following issuing the commands.

Creating the region in which mobs are spawning:
<a href="https://imgur.com/ktvks2Q"><img src="https://i.imgur.com/ktvks2Q.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/vGY0zI6"><img src="https://i.imgur.com/vGY0zI6.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/tChU682"><img src="https://i.imgur.com/tChU682.png" title="source: imgur.com" /></a>

Editing the region with "/rg edit Region0":
<a href="https://imgur.com/6FyHjjL"><img src="https://i.imgur.com/6FyHjjL.png" title="source: imgur.com" /></a>

Enabling the flag with "/rg flag mobspawn all false":
<a href="https://imgur.com/wFGc1n1"><img src="https://i.imgur.com/wFGc1n1.png" title="source: imgur.com" /></a>

Flag change successful:
<a href="https://imgur.com/qlpe3Ye"><img src="https://i.imgur.com/qlpe3Ye.png" title="source: imgur.com" /></a>

Then clearing all entites:
<a href="https://imgur.com/cONur5H"><img src="https://i.imgur.com/cONur5H.png" title="source: imgur.com" /></a>

Yet, mobs continued to spawn:
<a href="https://imgur.com/f8XCCV3"><img src="https://i.imgur.com/f8XCCV3.png" title="source: imgur.com" /></a>

When examing the config, I see no changes to the mob flags:
<a href="https://imgur.com/9RgURAF"><img src="https://i.imgur.com/9RgURAF.jpg" title="source: imgur.com" /></a>

**Comment by JimiIT92** [comment] 2018-04-23 19:02
That's because,standing from your screenshots, you didn't saved your changes after updating the flag ;)

**Comment by spruill7716** [comment] 2018-04-23 22:59
Didn't realize I was supposed to do that. I tried again and saved the region, which added the flag to the config, but mobs are still spawning. I included the config below:

https://www.dropbox.com/s/icfnx0xcw36naj0/eb3305f1-1d8c-4a14-aebf-af7e2e9c71d8.json?dl=0

**Comment by JimiIT92** [comment] 2018-04-25 10:53
I will check this issue. Consider that prevent mobs from spawning in a region will not prevent them from spawning in nearby or global regions, so make sure they are not mobs coming from that regions ;)

**Comment by spruill7716** [comment] 2018-04-25 19:41
Thank you. I looked again and disabled mobs on the global region and it still doesn't work. I set the local region to a higher priority but still with no avail.

**Comment by JimiIT92** [comment] 2018-05-05 16:49
Yes, that Custom Mod Spawner could be the cause as it could raise an event that the plugin doesn't handle. For the PVE part that should be fixed in version 2.8, wich will be released soon on the Sponge page right here ;)
https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/

**Comment by hellbringer616** [comment] 2018-05-31 12:35
Using 2.11 and Sponge API 7.1 - 3076 this issue appears to be resolved.

**Closed** 2018-06-01 19:12 UTC
Labels: bug
